Views Sort Plugin Generator
Chi-teck/drupal-code-generator pull request #27
Opened 2018-11-01 06:58 UTC by NickWilde1990

2018-11-04 14:51 UTC, Chi-teck commented on src/Command/Drupal_8/Plugin/Views/Sort.php
> +class Style extends BaseGenerator {
The class name should _Sort_ I presume.

2019-01-25 09:08 UTC, manuee commented on src/Command/Drupal_8/Plugin/Views/Sort.php
> +  protected $description = 'Generates views sort plugin';
```suggestion
  protected $description = 'Generates a views sort plugin';
```

2019-01-25 09:10 UTC, manuee commented on templates/d8/plugin/views/sort-plugin.twig
> +  }
Do we really need the defineOptions() method defined?

2019-01-25 09:15 UTC, manuee commented on templates/d8/plugin/views/sort-plugin.twig
> +  protected $usesRowPlugin = TRUE;
I  believe this is for sytle plugins only.

2019-01-25 09:15 UTC, manuee commented on templates/d8/plugin/views/sort-plugin.twig
> +  protected $usesRowClass = TRUE;
I  believe this is for sytle plugins only.

2019-01-25 09:17 UTC, manuee commented on templates/d8/plugin/views/sort-plugin.twig
> +  public function buildOptionsForm(&$form, FormStateInterface $form_state) {
This method is an exact copy of `SortPluginBase::buildOptionsForm()`, I dont think we need to add it to the generated plugin.

2019-01-25 09:20 UTC, manuee requested changes
Besides by previous comments, I believe the method most sort plugins will implement will be the `query(`) method. I propose we add it.

2020-08-11 08:38 UTC, Rahul-coder01 commented
https://wiki.almworks.com/display/structure/Sort+Generators

2024-05-20 17:17 UTC, Chi-teck commented
Seems not many people interested in this generator. Closing.

2024-05-20 17:17 UTC, closed without merging